### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by aydv** [msaroufim/Driver-Telematics-Kaggle-Neural-Net#1]
Hi msaroufim,

Thanks a lot for sharing your code and experience in this contest. I am at the moment studying the driving behaviour area and unfortunately axa has deleted the data for this contest. Do you happen to have the full dataset that you can share?

Many thanks again and look forward to your kind feedback,
Ankit

**Comment by msaroufim** [comment]
Hey Ankit,

I just checked and couldn't find it. I've reformatted my laptop a few times
in the past couple of years so apologize for that. You may find this
reference useful though
https://www.kaggle.com/c/axa-driver-telematics-analysis/discussion/20511

Thanks,
Mark

**Comment by aydv** [comment]
Thanks mark, for letting me know.

Warm Regards
ANkit
